spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  redis:
  data:
    redis:
      host: localhost
      port: 6379

  testcontainers:
    enabled: true
